### ISSUE TITLE
Uncomment make check

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/flex-feedstock#1]
As soon as bison binaries are up we can address https://github.com/conda-forge/flex-feedstock/blob/master/recipe/build.sh#L6-L10

**Comment by jakirkham** [comment]
Tried adding bison. Still failing 2 tests. :disappointed: Though it was 3 before.

**Comment by jakirkham** [comment]
Appears related to this [4yr old ticket](https://sourceforge.net/p/flex/mailman/message/30006125/).

**Comment by ocefpaf** [comment]
> Tried adding bison. Still failing 2 tests. :disappointed: Though it was 3 before.

That is a win IMO :wink:

**Comment by jakirkham** [comment]
Ha. Narrowed it down. This is the core issue, [bison dropped support for those functions](https://sourceforge.net/p/flex/bugs/169/). I know it is unbelievable. We can add the patch from the issue for now. Eventually, we will have to brave updating this stuff even though they are circular dependencies.

**Comment by jakirkham** [comment]
...or we could just do the 2.6.0 update, which will drop our existing patch.

**Comment by jakirkham** [comment]
Patched for now so that we have one last build of 2.5.39. Given that this was the last release of `flex` that built without `bison`, it seems important that we have a decent version that we are confident works.
